#override image placement for azure registry


services:
  elasticsearch:
    image: directoratehealth.azurecr.io/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - node.name=snowstorm
      - cluster.name=snowstorm-cluster
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch:9200"]
      interval: 1s
      timeout: 1s
      retries: 60
    ports:
      - 9200:9200
    mem_reservation: 4g

  snowstorm:
    image: directoratehealth.azurecr.io/snowstorm:latest
    container_name: snowstorm
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: >
        java -Xms2g -Xmx4g
        --add-opens java.base/java.lang=ALL-UNNAMED
        --add-opens java.base/java.util=ALL-UNNAMED
        -cp @/app/jib-classpath-file
        org.snomed.snowstorm.SnowstormApplicationports:
    ports:
    - 8080:8080

  browser:
    image: directoratehealth.azurecr.io/snomedct-browser:latest
    container_name: browser
    depends_on:
      - snowstorm
    environment:
      - API_HOST=http://snowstorm:8080/
    ports:
      - 80:80
    restart: always




volumes:
  elastic:
