name: Build and Push to ACR

on:
  push:
    branches: [ develop ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      # Login to azure container registry
      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER}}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USER}}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PW }}

      - name: log in to docker
        run: docker login

      - name: Build images using Docker Compose
        run: docker compose build

      - name: Push images using Docker Compose
        run: docker compose push
